barnardos/consent-form-builder

.eslintignore
.eslintrc
circle.yml
package.json
yarn.lock

Introduced eslint to keep styling of js consistent where possible. Uses rules defined by https://standardjs.com/ .
Can be used in an ide by installing an eslint module or from the command line and ci integration using npm run lint

Setup Linting tools for JS files.

---

docker-compose.yml

Setting EXTERNAL_PORT and/or DEBUG_PORT in the environment before launching the server with docker-compose will allow the developer to override the ports the server listens on, or the port debugging uses. Useful if running other server that already use the default 3000/26162

Allow developer to override the port the server binds to.

---

app/assets/stylesheets/barnardos/_type.scss
app/views/layouts/application.html.erb

Running Rails locally allows you to just put in the name of a font or use /assets/image to access assets but this breaks when deployed to Heroku.
Switched to helpers to load assets so they use the full hashed url on Heroku

Use asset helpers to work with Heroku

---

app/helpers/barnardos/action_view/form_helpers.rb
app/models/payment_type.rb
app/views/research_sessions/incentive.html.erb
features/step_definitions/question_steps.rb

Convert the incentive page to use the `FormHelper#vertical_radio_group` (instead of the ad-hoc HTML it had).

Incentive vertical radio

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/barnardos/_errorsummary.scss
app/views/research_sessions/_error_summary.html.erb
app/views/research_sessions/age.html.erb
app/views/research_sessions/focus.html.erb
app/views/research_sessions/incentive.html.erb
app/views/research_sessions/methodologies.html.erb
app/views/research_sessions/recording.html.erb
app/views/research_sessions/researcher.html.erb

* Styled error summary
* Put summary at top of screen above title
* Add link from summary item to field to allow navigation to field (fields currently missing this but will add later)

Created styles for error summary and clearer messages

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/barnardos/_checkbox.scss
app/assets/stylesheets/barnardos/_lists.scss
app/controllers/research_sessions_controller.rb
app/models/research_session.rb
app/presenters/research_session_presenter.rb
app/views/research_sessions/preview.html.erb
app/views/research_sessions/preview_consent_form.html.erb
config/routes.rb
features/printed_consent_forms.feature
features/step_definitions/consent_form_preview_steps.rb
features/step_definitions/question_steps.rb
features/step_definitions/session_review_steps.rb
spec/models/research_session_spec.rb

Don't quite know what to do with this. It's clearly a thing that produces a consent form, and it's tacked onto the end of the current process after the information sheet preview.  It's really intended as a "fill in the blank" for the [story](https://trello.com/c/QpzZjRjA/16-story-at-the-session-review-page-i-can-print-the-consent-form) that wasn't quite delivered.
But in order to get there (meet acceptance criteria) it needs a print stylesheet.
Ideally, the list items also need styling (default styles guessed at in e2546185b85feb57d6cc6756338b450f140e9463).

Consent form preview

---

Rakefile
circle.yml
lib/tasks/npm.rake

For [this chore](https://trello.com/c/ofglsmUl/28-run-a-build-healthcheck)
Lets us chain rake commands and have them execute in order. Puts npm
tasks in an npm: namespace, so `rake npm:lint` would run `npm run lint`
This has the side-effect of allowing us to run `bundle exec rake`
locally to run exactly what the CI server will run.

Use single build entry point

---

app/assets/stylesheets/barnardos/_textarea.scss

Browsers default to a system mono font for textrea so this has to be overriden to pickup the font family required for Barnardos components.

Fix issue with textarea font

---

app/assets/stylesheets/barnardos/_textarea.scss

Previously the style for the error indicator was being selected for all textareas, an additional selector for .has_error needed to be added.

Fix issue with textarea error indicator

---

app/assets/stylesheets/barnardos/_radio.scss

The radio control accepts a error parameter, which is an error by
convention. The control will then conditionally set the has-error class
on the wrapper and display the first error below the field.

Display error for radio lists if provided

---

.rubocop.yml
app/views/research_sessions/preview.html.erb
features/printed_consent_forms.feature
features/step_definitions/question_steps.rb
features/step_definitions/session_review_steps.rb
features/support/action_view.rb

[(2) Carry through formatting (i.e. line-breaks) from Form to to Print Format](https://trello.com/c/yA9an8mR/74-2-carry-through-formatting-ie-line-breaks-from-form-to-to-print-format)
As a researcher,
I want my research focus to appear with the minimal formatting I used on the entry page
So that I'm not terribly confused and frustrated

Preserve research focus linebreaks

---

.rubocop.yml

Rubocop on Windows defaults to check for line endings native to the OS, in the case of Windows this is CRLF, but the project is set to enforce uniform use of LF.
This Rubocop setting makes the linter check for LF no matter what the OS is used for linting.

Add support to lint Ruby with Rubocop on Windows

---

app/javascript/packs/application.js
app/javascript/vendor/hotjar.js

**NB: Ad blockers will kill this - disable or whitelist**
Added to `app/javascript/vendor`. It's a single anonymous function that
doesn't need to be referenced anywhere, so it's included with a require
that doesn't save any module reference.
If this is working you'll see a feedback logo at the bottom right of
your browser:

Add Hotjar script for feedback

---

.eslintignore
lib/tasks/npm.rake

`hotjar.js` produced 37 errors, but didn't fail the build. Although we'd want to exclude hotjar's script from our linting, it's been a useful canary.
Make sure tasks under `rake npm:*` bubble their exit code correctly rather than masking problems.

Linter js should fail build

---

.rubocop.yml
.rubocop_todo.yml
app/assets/stylesheets/app/session_preview.scss
app/controllers/research_sessions_controller.rb
app/helpers/research_sessions_helper.rb
app/models/research_session.rb
app/models/research_session/steps.rb
app/views/research_sessions/preview.html.erb
features/printed_consent_forms.feature
features/step_definitions/session_review_steps.rb
spec/helpers/research_sessions_helper_spec.rb
spec/models/research_session/steps_spec.rb
spec/models/research_session_spec.rb

As a researcher
I want to indicate the thing I want to edit in the preview
So that I can go directly to that page
- We've moved things related to wizard steps into a nested class `ResearchSession::Steps`
- There is no class method called `h` before you ask, @sl33p 
- Make it look not godawful (please, Obi-Wan-@ztolley, you are my only hope)
- [Fix header mismatches in three wizard steps](6b45aa6)
- [Move focus.html.erb label_options together](2fe3ffec5453357f788843235c3a93a371bfdc31)

Link back to steps from preview

---

app/helpers/barnardos/action_view/form_helpers.rb
spec/helpers/barnardos/checkbox_helper_spec.rb

Fill in a checkbox page and move away from it. Go back via the "Back" link or by entering the previous step's URL.
The checkboxes should show the values you chose
The checkboxes are blank.
This PR fixes the above issue

Fix checkbox persistence

---

app/javascript/components/highlightcontrol.js

IE does not allow iteration of nodelist.
Convert nodelist to array to allow iteration.

Fix compatibility with IE9-11 js

---

app/javascript/lib/exit_warn.js
app/javascript/packs/application.js

Most browsers warn the user that they are leaving a page and have made changes to a form. This small polyfill listens for form changes and adds an event to warn the user if they try to leave the page, unless they submit the form in which case it removes the event handler that does that.
The reason the event is added and taken away is that if we just try to return false or something from that event handler it puts that on the screen. The easiest way to handle things is remove the even handler altogether when you submit a page as it's no longer needed.

Warn on exit

---

app/assets/stylesheets/app/session_preview.scss
app/assets/stylesheets/barnardos/_checkbox.scss
app/assets/stylesheets/barnardos/_radio.scss
app/assets/stylesheets/barnardos/_textarea.scss
app/assets/stylesheets/barnardos/_textfield.scss
app/views/gallery/index.html.erb
app/views/research_sessions/focus.html.erb
app/views/research_sessions/methodologies.html.erb
app/views/research_sessions/recording.html.erb

While making #45, we noticed a couple of problems:
1. A few headers had the wrong closing tags 
2. Some options to a helper were duplicated and causing a "last in wins" scenario. Fixing this necessitated an extra CSS change.

Fix headers and hints

---

Gemfile
Gemfile.lock

Heroku doesn't get its ruby version from .ruby-version. It relies
on the Gemfile. Set that the same by reading the .ruby-version file
here.

Add ruby version to Gemfile for Heroku

---

app.json

Heroku requries an app.json to tell it how to configure PR created instances, this is that app.json

Add app.json to support Heroku PR deployment

---

app/assets/stylesheets/barnardos/_page.scss
app/helpers/application_helper.rb
app/views/layouts/application.html.erb
features/aids_for_devops.feature
features/step_definitions/aids_for_devops_steps.rb
spec/helpers/application_helper_spec.rb

- Adds a link to the current `HEAD` commit on Github in a minimal footer
- Dependent on github links
- Dependent on presence of `HEROKU_SLUG_COMMIT` if in production
- Will show 'Release: unavailable' for any environment without
`HEROKU_SLUG_COMMIT` or a git repo with a `HEAD`
We can do better than this, but this at least gives PM and DM an idea
of what's live. We can get to reasonable release naming and a changelog
next – this ticket is "minimal what's live"

Add a link to the current release SHA

---

app/models/methodologies.rb
app/models/recording_methods.rb
app/models/research_session.rb
app/models/research_session/steps.rb
app/presenters/research_session_presenter.rb
app/views/research_sessions/methodologies.html.erb
app/views/research_sessions/recording.html.erb
db/migrate/20170809140248_add_other_methodology_and_other_recording_method.rb
db/schema.rb
features/printed_consent_forms.feature
features/step_definitions/question_steps.rb
features/step_definitions/session_review_steps.rb
features/support/action_view.rb
features/support/rspec_html_matchers.rb
spec/models/research_session_spec.rb
spec/presenters/research_session_presenter_spec.rb

_When I am using a methodology or recording method not listed on the page, I want to be able to add my own, so I can provide the correct information on the form._
*NB* The "Nice to have" is not done – I have one day left before holiday and it's best to spend that clearing the things that are in review rather than starting new work. Also, it's a nice splittable bit of JS, so if you want a separate card, I've [made one](https://trello.com/c/W7HSG0qw/114-hide-other-text-fields-unless-other-selected-on-methodologies-and-recording-methods) in the Inbox.

Add 'other' checkboxes

---

app/assets/stylesheets/barnardos/_page.scss

Oops. Only resized my browser, so missed this on scroll. Go with
`position: fixed` rather than `absolute`.

Make the footer stick to the viewport

---

app/assets/stylesheets/app/consent_form_preview.scss
app/assets/stylesheets/barnardos/_page.scss

- Stop using colour literals. Use only those in _colours.scss
- Selectors: one per line
- Concise-imify a padding def
Before:
```bash
➜  consent-form-builder-rails git:(master) npm run lint:styles
> myapp@ lint:styles /Users/russ/dev/bdos/consent-form-builder-rails
> sass-lint -c .sass-lint.yml 'app/assets/stylesheets/**/*.scss' -v -q
app/assets/stylesheets/app/consent_form_preview.scss
21:30  warning  Color 'black' should be written in its hexadecimal form #000000              no-color-keywords
21:30  warning  Color literals such as 'black' should only be used in variable declarations  no-color-literals
29:16  warning  Selectors must be placed on new lines                                        single-line-per-selector
app/assets/stylesheets/barnardos/_page.scss
44:21  warning  Color …
```

Fix Sass warnings

---

app/assets/stylesheets/barnardos/_progress.scss
app/presenters/research_session_presenter.rb
app/views/research_sessions/_back_link.html.erb
app/views/research_sessions/_progress.html.erb
app/views/research_sessions/age.html.erb
app/views/research_sessions/focus.html.erb
app/views/research_sessions/incentive.html.erb
app/views/research_sessions/methodologies.html.erb
app/views/research_sessions/recording.html.erb
app/views/research_sessions/researcher.html.erb
config/locales/en.yml

Uses a visual indicator to let the user know where they are in the journey and navigate back and forward as needed.
- Users can always navigate back
- Users can only navigate forward if they have previous filled in a future screen
- Link to the preview page when all sections are complete.

Show progress

---

app/helpers/barnardos/action_view/form_helpers.rb
spec/helpers/barnardos/text_area_helper_spec.rb

The labelled text are tag did not use the text options passed to it, so it was not possible to set options such as placeholder. This has been corrected.

Fix missing support for text_options in textrea

---

app/views/research_sessions/_progress.html.erb
config/initializers/inflections.rb
config/locales/en.yml

If we use `I18n.translate`, translations have to exist in `en.yml`,
otherwise errors make it into the markup (see below).
`String#humanize` doesn't have this issue
(but still lets us specify our own translations).
Before, in _progress output (because we didn't have `en.time_equipment`):
```HTML
<a href="/questions/time_equipment">
<span class="translation_missing"
title="translation missing: en.time_equipment">
Time Equipment
</span>
</a>
```
After, including a `#human` call in `initializers/inflections.rb`:
```HTML
<a href="/questions/time_equipment">Time / equipment</a>
```
Because the rest of the progress titles are conventional, (for example,
`:methodologies.to_s.humanize => 'Methodologies'`) we don't need
special cases for anything else and can remove the obligation to
translate in …

Prefer #humanize/inflections over translations

---

app/views/research_sessions/preview.html.erb

Fix empty preview researcher

---

app/javascript/components/conditional_subfields.js
spec/javascript/components/conditional_subfield_spec.js

Disable conditional subfields, don't clear the value
We weren't ever restoring the value, but were wiping it on hide so it
made our sometimes-hidden fields look like they'd forgotten the value
from `@research_session`.

Disable conditional subfields, don't clear value

---

app/assets/stylesheets/barnardos/_textarea.scss
app/assets/stylesheets/barnardos/_textfield.scss

Added vertical padding to .textfield and .textarea elements
Before and after shots:

Design review

---

app/models/research_session/steps.rb

We'd forgotten to permit the `researcher_other` boolean field, meaning
that when we returned to the researcher step, even though we'd filled
out a second researcher, that portion of the form remained hidden.
Allow the parameter such that the second researcher is shown.

Make "other researcher" persistent

---

app/views/research_sessions/data.html.erb
config/locales/en.yml

Rails has a place for this kind of thing, in `en.yml`. Under the `en.activerecord.attributes.<model_name>.<attr_name>` keys, add labels for things that aren't currently clear in validations.  Later, with `form_with` and our own builder, we can stop using `labelled_text_field_tag` and duplicating these labels across views, and start using `form.label`.  
Use a specialised formatter for error messages such that the labels are properly quoted (otherwise we get strings that don't read very well)
We were missing a 'the' in a sentence

Data sharing label

---

app/assets/stylesheets/barnardos/_checkbox.scss
app/assets/stylesheets/barnardos/_fieldset.scss
app/assets/stylesheets/barnardos/_progress.scss
app/assets/stylesheets/barnardos/_radio.scss
app/views/research_sessions/data.html.erb
app/views/research_sessions/expenses.html.erb
app/views/research_sessions/incentive.html.erb
app/views/research_sessions/methodologies.html.erb
app/views/research_sessions/purpose.html.erb
app/views/research_sessions/recording.html.erb
app/views/research_sessions/researcher.html.erb
app/views/research_sessions/time_equipment.html.erb
app/views/research_sessions/topic.html.erb

* Adjusted the progress bar to result in a consistent height.
*  Swited page headings to consistent structure for consistent heading sizes and spacing
* Adjusted radio headings to fix spacing oddity.

Improve page spacing consistency

---

app/controllers/gallery_controller.rb

This was missed; no longer exists

Remove last FormTagHelper reference

---

app/controllers/research_sessions_controller.rb
app/helpers/research_sessions_helper.rb
app/presenters/research_session_presenter.rb
app/views/research_sessions/_progress.html.erb
app/views/research_sessions/index.html.erb
config/routes.rb
features/printed_consent_forms.feature
features/step_definitions/aids_for_devops_steps.rb
features/step_definitions/question_steps.rb
features/step_definitions/session_review_steps.rb
spec/controllers/research_sessions_controller_spec.rb

When I create a consent form, I want to be able to return to the form, so I can carry on where I left off.
When I have finished creating a form, I want to be able to return to the form, so I can print it out and use it for my research sessions.
Make the URL of the research session addressable. The current state: `/questions/researcher` should change to e.g.
`/sessions/1234/questions/researcher`
or
`/sessions/1234-autogenerated-text-from-topic/questions/researcher`
Also address the session creation semantics problem, i.e. it was
possible to create a session by visiting `/start`. Make that a POST to
`/research-sessions` instead, which is more Rails-y and lets us just add
`:create` to the resources definition in `routes.rb`

Make research sessions addressable

---

Gemfile
Gemfile.lock
spec/factories/research_session.rb
spec/models/research_session_spec.rb
spec/rails_helper.rb
spec/support/factory_girl.rb

There was a lot of [duplication](https://github.com/barnardos/consent-form-builder-rails/blob/master/spec/models/research_session_spec.rb#L279-L289) in `research_session_spec.rb` with respect to setting up models. Suddenly we need to do the same kind of thing again in order to set up tests to [redirect to partially-completed forms](https://trello.com/c/Su0Kmc51/150-make-urls-returnable#comment-59bfa06495ff1052eadba0d3).
Rather than pollute `research_controller_spec.rb` with similar duplication, make a factory for each `ResearchSession::Steps` step.

Convert to factory_girl

---

app/helpers/barnardos/action_view/form_helper.rb
spec/helpers/barnardos/action_view/form_helper_spec.rb

We were relying on the Rails `FormHelper#label` method to look up a
label from translations for us. Unfortunately this was inside another
label. Really we need the translation on its own, which is... well, it's
pretty ugly (nil first param as we don't have an object, need to make
the rest of the params strings, need to point to the idiomatic home for
labels as a scope).

Avoid a double label in labelled_text_area

---

app/views/research_sessions/_button_bar.erb
app/views/research_sessions/data.html.erb
app/views/research_sessions/expenses.html.erb
app/views/research_sessions/incentive.html.erb
app/views/research_sessions/methodologies.html.erb
app/views/research_sessions/purpose.html.erb
app/views/research_sessions/recording.html.erb
app/views/research_sessions/researcher.html.erb
app/views/research_sessions/time_equipment.html.erb
app/views/research_sessions/topic.html.erb

Scarily close to the OK button, even though you can cancel your cancel
by clicking the 'back' button in your browser, it is still dangerous
ju-ju. Remove it, and rename the partial it appears in so as not to
mislead

Remove the cancel button

---

app/helpers/research_sessions_helper.rb
spec/helpers/research_sessions_helper_spec.rb

The rails `_path` method here *can* accept a model, but the trouble is
it's really getting a presenter that doesn't behave in quite the same
way. Since only the `ResearchSession#id` is used and the presenter already
has that, pass that through instead
(and update the test double to respond to `:id`)

Fix links in preview returning to steps

---

app/controllers/research_sessions_controller.rb
app/helpers/barnardos/action_view/form_helper.rb
app/javascript/components/conditional_subfields.js
spec/controllers/research_sessions_controller_spec.rb
spec/javascript/components/conditional_subfield_spec.js

Fix the above, which is a 400 Bad Request resulting from an error thrown in `ResearchSessionsController#question_params` (the `permit` part) when no value is given for either of `methodologies` or `recording_method` due to no checkboxes being selected. 
What *should* happen is that the request is good but validation fails with a meaningful error message. What made this *not* happen is that we were using `include_hidden: false` as an option to `collection_check_boxes` to avoid a problem with `ConditionalSubfields.js` not being aware of hidden fields, overriding Rails' default behaviour and causing nothing to be passed when at least a blank value is required.
1. Make `ConditionalSubfields.js` aware of blank hidden fields. This is good enough for our use case.
1. Remove the `include_hidden: …

Fix strong param error for blank checkboxes

---

app/assets/stylesheets/barnardos/_page.scss

On smaller viewports, the header was causing the page to overflow horizontally causing a scroll to black space. Adding the gutter space with padding allows the space to be contained within the width of the element.

Fix header width on mobile size viewports

---

app/assets/stylesheets/barnardos/_checkbox.scss
app/assets/stylesheets/barnardos/_radio.scss
app/assets/stylesheets/barnardos/_textarea.scss
app/assets/stylesheets/barnardos/_textfield.scss
app/assets/stylesheets/barnardos/_vars.scss
app/helpers/barnardos/action_view/form_helper.rb

Tidying up the error state styles for textfields and textareas that are present in the screenshot featured in https://github.com/barnardos/consent-form-builder-rails/pull/93. These updates bring the styles more inline with the styleguide.

Tidy up the inline error styles

---

app/assets/stylesheets/barnardos/_checkbox.scss

To restore tab functionality, swap `display: none` in the
`checkbox-group__input` for an `absolute` positioning within its div and an
opacity of 0 such that it responds once again to browser events.
Then style `:focus` the same as `:hover` for `.checkbox-group__input`, and
combine the styles for a selected focussed check box.

Allow tabbing in checkboxes

---

app/views/research_sessions/time_equipment.html.erb

Make the session date and time truely optional
Change the minute dropdown to be in steps of 15 to make it easier to select.

Improve session date time entry

---

app/views/research_sessions/researcher.html.erb

Last question should not read "/ participants" it should say "/ observers"

Replace 'participants' with 'observers' on researcher page

---

.rubocop.yml
app/presenters/research_session_presenter.rb
app/views/research_sessions/preview.html.erb
config/locales/en.yml
features/step_definitions/consent_form_preview_steps.rb
features/step_definitions/question_steps.rb
features/support/preview_checker.rb
spec/factories/research_session.rb
spec/presenters/research_session_presenter_spec.rb

... is to provide an area where we can argue about copy / the behaviour of the preview page and verify that copy for the happy path. To that end, it's added some checks testing the eventual copy, and it's probably an improvement over what currently happens in production, but it's a work in progress. **It shouldn't be merged** until we've had a chance to talk about things.
The commits happen pretty much in order of screen flow. The first commit adds some null checks on the preview content (because we weren't checking much on that page).
The following commits fill those checks in.

Preview everything

---

app/assets/stylesheets/barnardos/_print-section.scss

Space around '*' required in _print-section.scss

Fix sass-lint warning

---

spec/controllers/research_sessions_controller_spec.rb
spec/factories/research_session.rb
spec/models/research_session_spec.rb
spec/presenters/research_session_presenter_spec.rb

So far, we've had one solitary set of factories registered with the
same names as all the steps, namely:
* `:researcher`
* `:topic`
* `:purpose` .. and so on, with each factory dependent on the previous.
Now we need an actual `:researcher` factory for ([this story](https://trello.com/c/kpHLeXSK/122-5-add-another-researcher)), that `:researcher`
registered factory name needs to move.
Take the opportunity to move to traits.
`build_stubbed :researcher` – would return a `ResearchSession` with a
status valid at the `:researcher` step and the researcher details
filled in
`build_stubbed :research_session, :step_researcher` – will return a
`ResearchSession` with a status of `:researcher` and the researcher
details filled in. No longer misleading!

Move to traits for ResearchSession factories

---

app/views/research_sessions/preview.html.erb

Our rebase left some fields in preview twice.
Tests wouldn't pick this up. I've cherry-picked this from @joelcarr's branch as a hotfix.

Remove duplicated fields from preview page

---

spec/controllers/research_sessions_controller_spec.rb

Was slow (manifested in first test hanging for seconds) and has been unnecessary for a while. We don't care what was rendered, just that the right template was chosen.

Stop rendering views in controller spec

---

app/helpers/barnardos/action_view/form_builder.rb
app/helpers/barnardos/action_view/form_helper.rb
spec/helpers/barnardos/action_view/form_builder_spec.rb

Because of [this branch](https://trello.com/c/kpHLeXSK/122-5-add-another-researcher), we found that in some circumstances – chiefly when using `fields_for` – our `barnardos_form_with` fields weren't having their values populated when returning to wizard steps.
We discovered that it's the responsibility of a `FormBuilder` to call `objectify_options` on a vanilla `options` hash passed to underlying Rails tag generators such that when we can't simply send an attribute name to a named model (because, for example, we're in a nested object in a `fields_for` block), Rails can consult the `options` hash to discover an object from which it can populate the value.
For each of our four methods, ensure this `options` hash is routed to the correct Rails helper. In the case of the two text field types, …

Fix fields for formbuilder

---

app/helpers/research_sessions_helper.rb
app/views/research_sessions/preview.html.erb
spec/views/research_session/preview.html.erb_spec.rb

The info sheet only refers to the reader as the participant/respondent.
Adding in conditional copy that makes it clear who the participant is
and what the research is asking of them depending if they can give
consent.
Will run through with Jess to ensure it makes sense. Can you see any other bits that might be missing?

Add reference to child for respondents who cant give consent

---

CHANGELOG.md
Gemfile
Gemfile.lock
app/controllers/changelogs_controller.rb
app/views/changelogs/show.html.erb
config/routes.rb

Add a CHANGELOG.md and serve if from `/changelog`
Comes with no tests at present, given that this was for a little spike.
Add a CHANGELOG.md using the suggested changelog standard for the
vandamme gem (used by Gemnasium). It's not particularly mature, but
it's less important that we agree on its content; more that we agree
on something that communicates our changes.

Changelog and rudimentary serving from /changelog

---

app/controllers/research_sessions_controller.rb
app/models/research_session.rb
app/presenters/research_session_presenter.rb
app/views/research_sessions/preview.html.erb
config/locales/en.yml
db/migrate/20171005095604_replace_age_with_consent.rb
db/schema.rb
features/support/preview_checker.rb
spec/models/research_session_spec.rb
spec/presenters/research_session_presenter_spec.rb
spec/views/research_session/preview.html.erb_spec.rb

Since we only talk about the ability to give consent, storing age is
misleading. Instead, use a query string parameter `able_to_consent` to
determine the preview content at the end of the wizard.
Since this is now a view concern only, move
`ResearchSession#able_to_consent?` and `ResearchSession#unable_to_consent?`
to `ResearchSessionPresenter`. Pass the ability to consent or otherwise
directly from the query string to the presenter in the controller.

Remove the concept of age

---

app/assets/stylesheets/barnardos/_button.scss

CSS to display a pointy finger hand when hovering buttons.
Why: because affordances make things easier to understand, and the little, single white-gloved hand lets you imagine you're remotely operating a Michael Jackson simulator.

Added cursor:pointer to buttons so people know they can click it

---

app/views/research_sessions/researcher.html.erb

The yes/no option for `/research` was laid out opposite to the rest of the form causing some confusion for our users.

Ensure yes/no radios are consistent

---

CHANGELOG.md
app/assets/stylesheets/application.scss
app/assets/stylesheets/barnardos/_selectfield.scss
app/views/gallery/index.html.erb
app/views/research_sessions/preview.html.erb

Created styles for the select fields from the forms designs. They
haven't been applied to the date/time select field due to its'
dependency with the rails form builder helper.

add styles for select fields

---

.sass-lint.yml
app/controllers/research_sessions_controller.rb
app/views/research_sessions/_progress.html.erb
spec/controllers/research_sessions_controller_spec.rb

When going back from your completed form to edit a step, clicking 'continue' caused the subsequent progress bar steps to become inactive forcing the user to keep clicking continue. This PR fixes this issue as well as:
- Setting styles to always show if a step as been completed, not just previous steps
- Giving the preview step the completed style when viewing previous steps
- Updating the sass lint to not warn us about using 3-value shorthand for box model styling
Before:
After:

BUG: returning to previous steps in the preview bar disables links to subsequent steps

---

CHANGELOG.md
app/controllers/research_sessions_controller.rb
app/helpers/research_sessions_helper.rb
app/views/research_sessions/_button_bar.erb
features/printed_consent_forms.feature
features/step_definitions/question_steps.rb
features/step_definitions/session_review_steps.rb
spec/controllers/research_sessions_controller_spec.rb
spec/helpers/research_sessions_helper_spec.rb

As a researcher
I want to go straight back to the preview when I've edited just one thing
So that I don't have to continue through all the wizard steps again

Return to preview after edit

---

CHANGELOG.md
app/assets/stylesheets/_reset.scss

The gutters for the main content were not being displayed on IE11. This
is because IE11 did not apply the style `display: block;` to the `main`
tag.
Before:
After:

Fix IE11 spacing issue

---

CHANGELOG.md
app/javascript/components/conditional_subfields.js

We need to use the lodash polyfill for `includes` script and not the inbuilt browser
emacscript `array.includes`

Allow additional subfields to show/hide on IE11

---

CHANGELOG.md
app/assets/stylesheets/barnardos/_selectfield.scss

IE11 was showing 2 dropdown arrows for the selectfield styles. This
commit adds the pseudo element for IE to remove it's default styles.
Before:
After:

Ensure selectfield doesn't show 2 arrows on ie11

---

CHANGELOG.md
app/assets/stylesheets/print.scss

The release hash and hotjar icon appear on print styles which might
obscure the content.

Hide release hash and hotjar from print styles

---

CHANGELOG.md
app/models/research_session/steps.rb
app/views/research_sessions/preview.html.erb
app/views/research_sessions/time_equipment.html.erb
config/locales/en.yml
db/migrate/20171017154810_add_location_to_time_equipment.rb
db/schema.rb
features/step_definitions/question_steps.rb
features/support/preview_checker.rb

While acknowledging that time/equipment is now a bad name, add an
optional location to the time/equipment step. We need a DB migration for
this and an associated label in en.yml. The preview has a simple
sentence with a presence check for the optional field.

Add location to time and equipment

---

CHANGELOG.md
app/assets/stylesheets/barnardos/_accessibility.scss
app/assets/stylesheets/barnardos/_checkbox.scss
app/assets/stylesheets/barnardos/_progress.scss
app/assets/stylesheets/barnardos/_radio.scss
app/helpers/barnardos/action_view/form_helper.rb
app/views/layouts/application.html.erb
app/views/research_sessions/_progress.html.erb
app/views/research_sessions/data.html.erb
app/views/research_sessions/expenses.html.erb
app/views/research_sessions/incentive.html.erb
app/views/research_sessions/methodologies.html.erb
app/views/research_sessions/purpose.html.erb
app/views/research_sessions/recording.html.erb
app/views/research_sessions/researcher.html.erb
app/views/research_sessions/time_equipment.html.erb
app/views/research_sessions/topic.html.erb
spec/helpers/barnardos/action_view/form_helper_spec.rb

Improves keyboard navigation by placing you in the first field on each form (excepting time/equipment, for which there is a separate [card](https://trello.com/c/91fUZw28/189-3-change-the-date-time-form-fields-to-not-use-formdatetimeselect))
Hides the "skip to main content" link, although it is still in the tab order for screen readers.
We needed to add a radio button focus style, which we had previously done for check boxes, so this PR also fixes [radio buttons not appearing in tab order](https://trello.com/c/dRpWMj0g/220-tabbing-through-radio-buttons-isnt-working).

Autofocus first field / hide "skip to content"

---

CHANGELOG.md
app/models/research_session/steps.rb
app/views/research_sessions/preview.html.erb
app/views/research_sessions/time_equipment.html.erb
config/locales/en.yml
db/migrate/20171019140044_replace_session_date_time_with_text.rb
db/schema.rb
features/step_definitions/question_steps.rb
features/support/preview_checker.rb
spec/factories/research_session.rb
spec/views/research_session/preview.html.erb_spec.rb

Remove the date type `start_datetime` attribute and replace it with a
simpler `when_text` field. Autofocus that field and add a label for it in
`en.yml`.
Comes with a complicated two-way migration to generate nice-looking text
from the old dates and perform best efforts to roll back should that be
required.
All the work is pretty much making the tests pass.
Result:

Swapped session date field for simple text

---

CHANGELOG.md
app/assets/stylesheets/app/session_preview.scss
app/assets/stylesheets/barnardos/_colours.scss
app/helpers/research_sessions_helper.rb
app/presenters/research_session_presenter.rb
app/views/research_sessions/preview.html.erb
config/locales/en.yml
spec/helpers/research_sessions_helper_spec.rb
spec/presenters/research_session_presenter_spec.rb

Style the highlight edit links on the preview page to not be so harsh. This will make the final preview page easier to read for the users. Also removed empty html that was being outputted.
After:
Before:

Style the links and highlights on the preview page

---

Gemfile
Gemfile.lock
spec/factories/research_session.rb
spec/support/factory_girl.rb

While the etymology of FactoryGirl might have been innocent enough,
let's not pretend we can hire for diversity while knowingly
perpetuating a harmful stereotype. Go gender-neutral, it makes things
better.
And thanks, ThoughtBot, for being ThoughtfulBot.
https://github.com/thoughtbot/factory_bot/blob/master/NAME.md

Change FactoryGirl to FactoryBot

---

features/step_definitions/named_session_steps.rb

Post-merge of two unrelated PRs (session-naming and factory-bot
branches), we've ended up with a build-breaked stray FactoryGirl
reference.
Replacing it here.

Replace stray FactoryGirl reference

---

CHANGELOG.md
app/helpers/application_helper.rb
app/presenters/research_session_presenter.rb
app/views/layouts/application.html.erb
config/locales/en.yml
spec/helpers/application_helper_spec.rb

Make page titles reflect where we currently are in the process.
This also points out that our "preview" stage is a bit convoluted –
a session will be at the "incentive" step. We don't really have a
"finished" or "preview" state. We should, but that's tech debt.

Create page titles for each step

---

app/javascript/components/share.js

Fixup 8ba6145 to include the desired copy to clipboard functionality
required for the new share UI.

Add copy functionality for copy button

---

CHANGELOG.md
app/models/research_session/steps.rb
app/views/research_sessions/expenses.html.erb
app/views/research_sessions/where_when.html.erb

The :food_provided value does not relate to what the participant can
expense. Move the :food_provided value to the where_when step.

Move :food_provided to bottom on where_when step

---

CHANGELOG.md
app/models/research_session/steps.rb
app/views/research_sessions/preview.html.erb
app/views/research_sessions/questions/researcher.html.erb
config/locales/en.yml
db/migrate/20171108111544_add_job_title_to_researcher.rb
db/schema.rb
features/support/preview_checker.rb
features/support/step_completions.rb

As a consent form author
I want to be able to provide researcher job title
so that participant can understand who are they meeting

Add job title

---

CHANGELOG.md
app/controllers/research_sessions/questions_controller.rb
app/models/research_session.rb
spec/controllers/research_sessions/questions_controller_spec.rb
spec/models/research_session_spec.rb

> As a user
> I want to be able to use currency character in money fields
> So that it doesn't affect the saved amount
Add validation to currency fields to ensure numerical values are given.
Strip '£' as it is a common use case.

Ignore '£' in currency fields

---

CHANGELOG.md
app/assets/stylesheets/barnardos/_radio.scss
app/helpers/research_sessions_helper.rb
app/models/research_session.rb
app/models/research_session/steps.rb
app/models/shared_with.rb
app/views/research_sessions/preview.html.erb
app/views/research_sessions/questions/storing.html.erb
config/locales/en.yml
db/migrate/20171116154338_remove_shared_use.rb
db/schema.rb
features/support/preview_checker.rb
features/support/step_completions.rb
spec/factories/research_session.rb
spec/helpers/research_sessions_helper_spec.rb
spec/models/research_session_spec.rb

> As a researcher
> I want to make sure I am choosing the right option regarding storing information
> So that the created consent form provides true info and is GPDR compliant
Add an extra `anonymised` value to `SharedWith::NAME_VALUES` and change/internationalise the text for that and all other options. Map this to finished paragraphs on the preview.
This PR supersedes #148 for the acceptance criteria related to the above, but that older PR still has changes that are not related to this card. #148 should be analysed for outstanding GDPR changes and those changes should be extracted to separate cards.

GDPR compliance for storing step

---

CHANGELOG.md
app/views/research_sessions/preview.html.erb

Slight difference in copy between Google Doc and the helper which switches between you/your child. The helper has been used to maintain consistency.

Add "Sharing information" section to info sheet

---

CHANGELOG.md
app/views/research_sessions/preview.html.erb
spec/views/research_sessions/preview.html.erb_spec.rb

Removes "Do I have to take part" section. 
Changes tests which relied on "Do I have to take part copy" to test consent switch to test different copy.

Remove "Do I have to take part?" from info sheet

---

CHANGELOG.md
app/helpers/research_sessions_helper.rb
app/presenters/research_session_presenter.rb
app/views/research_sessions/preview.html.erb
features/support/preview_checker.rb
spec/presenters/research_session_presenter_spec.rb
spec/views/research_sessions/preview.html.erb_spec.rb

> As a research participant
> I want my Information Sheet to be as simple as possible
> So that I can understand what I am consenting to
This PR combines two related cards:

Create "Session Details" section

---

CHANGELOG.md
app/helpers/research_sessions_helper.rb
app/views/research_sessions/preview.html.erb
features/support/preview_checker.rb

We re-ordered the last bits of the page according to the [document](https://docs.google.com/document/d/1j8HWIUxYyquEZb9RpnZYBVX1SFtwEYg7TqRA3lfO9bI/edit).
We also found that there was no card for:
- Moving preview "storing" section to "confidentiality"
- Remove "Will what I say be kept confidential?"
- Removing extraneous "may" from "About taking part"
- Renaming incorrect "concerns" id to "decide"
Rather than open new cards we've just mopped those up here.

Order preview headers

---

Gemfile
Gemfile.lock
package.json
spec/views/research_sessions/preview.html.erb_spec.rb
yarn.lock

Upgrade webpacker to 3.0.2  …
- **Fixes compilation of assets in test environment** (avoids tests running
against stale React components)
- Also apply the following commands as per webpacker upgrading docs:
- `yarn upgrade @rails/webpacker --latest`
- `yarn upgrade webpack-dev-server --latest`
Note that following the upgrade to webpacker 3.x, js-using specs
(preview.html.erb_spec at time of writing) will now be **significantly
(2x) slower if you aren't running webpack-dev-server** when you test (it
looks like webpack-dev-server can manage the state of the compilation,
and in its absence, more compiles are invoked)

Fix test webpacker compilation

---

CHANGELOG.md
app/views/research_sessions/preview.html.erb

The heading is 'Review' which gives no context of the consent form it is
titling.
Update the copy to relate to the consent form.

Update 'consent form' heading

---

CHANGELOG.md
Rakefile
app/controllers/research_sessions/questions_controller.rb
app/helpers/research_sessions_helper.rb
app/javascript/components/ResearcherPreviews/index.js
app/javascript/components/ResearcherPreviews/index.test.js
app/javascript/components/Shared/PreviewBase.js
app/javascript/components/Shared/WhatHappensInThisResearchSession.js
app/javascript/components/TopicPurposePreviews/index.js
app/javascript/components/TopicPurposePreviews/index.test.js
app/models/research_session/steps.rb
app/views/research_sessions/preview.html.erb
app/views/research_sessions/questions/researcher.html.erb
app/views/research_sessions/questions/topic.html.erb
spec/helpers/research_sessions_helper_spec.rb

> As a researcher
> I want to see how I am affecting the preview as I edit live values
> So that my changes are obvious and I don't have to skip between steps
Add a live preview to topic. Use the same component on the preview.
We noticed that Jest wasn't being run as part of the main build. Oops! The `ResearcherPreviews/index.test.js` tests were broken for this reason (they referred to old copy). 
1. fix those, and 
1. add Jest to the main build, and
1. fix a problem with `ResearcherPreviews` where `you_or_your_child` wasn't being added
1. fix a problem with `ResearcherPreviews` where the phone # wasn't being rendered
(and don't yet care about)

Live preview topic/purpose

---

CHANGELOG.md
app/javascript/components/ResearcherPreviews/index.js
app/javascript/components/Shared/PreviewBase.js
app/javascript/components/TopicPurposePreviews/index.js

Tried to get live preview working on staging
That live preview worked
Live preview remained static.
We were relying on `this.constructor.name` to wire up our oninput events
unobtrusively, but uglifier mangles those names by default in every
environment outside of test, CI and dev.
Mandate a componentName method which must return the same name as as the
class.

Fix live previews broken by PreviewBase

---

CHANGELOG.md
app/assets/stylesheets/app/consent_form_preview.scss
app/assets/stylesheets/app/session_preview.scss
app/assets/stylesheets/barnardos/_lists.scss
app/assets/stylesheets/barnardos/_page.scss
app/assets/stylesheets/barnardos/_print-section.scss
app/assets/stylesheets/barnardos/_progress.scss
app/assets/stylesheets/barnardos/_reactive-container.scss
app/assets/stylesheets/barnardos/_reactive-preview.scss
app/assets/stylesheets/barnardos/_split-link.scss
app/assets/stylesheets/barnardos/_type.scss
app/assets/stylesheets/barnardos/_vars.scss
app/assets/stylesheets/print.scss
app/javascript/components/Shared/FindOutMore.js
app/javascript/components/Shared/WhatHappensInThisResearchSession.js
app/javascript/components/TopicPurposePreviews/index.js
app/views/layouts/application.html.erb
app/views/research_sessions/new.html.erb
app/views/research_sessions/preview.html.erb
app/views/research_sessions/questions/expenses.html.erb
app/views/research_sessions/questions/incentives.html.erb
app/views/research_sessions/questions/methodologies.html.erb
app/views/research_sessions/questions/recording.html.erb
app/views/research_sessions/questions/researcher.html.erb
app/views/research_sessions/questions/storing.html.erb
app/views/research_sessions/questions/topic.html.erb
app/views/research_sessions/questions/where_when.html.erb

- Apply font sizes to copy / headings from the Barnardo's styleguide
- Elements should use `margin-top` to create flow for content
- Reduce width of content to make the lines shorter therefore easier to read
- Ensure print styles make the final outcome look like a document rather than a website

Apply design rules featured in the original Barnardo's styleguide

---

CHANGELOG.md
app/helpers/barnardos/action_view/form_helper.rb
app/javascript/components/RecordingMethodsPreviews/index.test.js
app/javascript/components/ResearcherPreviews/index.test.js
app/javascript/components/Shared/DisplayAdditionalCopy.js
app/javascript/components/Shared/DisplayAdditionalCopy.test.js
app/javascript/components/Shared/Output.js
app/javascript/components/Shared/Output.test.js
app/javascript/components/Shared/PreviewBase.js
app/javascript/components/Shared/WhichWeWillRecordUsingSentence.js
app/javascript/components/Shared/WillAnyoneKnowWhatISayInTheDiscussion.js
app/javascript/components/StoringPreviews/index.js
app/javascript/components/StoringPreviews/index.test.js
app/javascript/components/TopicPurposePreviews/index.test.js
app/views/research_sessions/preview.html.erb
app/views/research_sessions/questions/storing.html.erb

Implements live preview for the "storing" step, we've also made the following changes;
* Refactored <Output> to include `data-field` to return field names (to help with testing).
* Updated radio button helper code to accept input params
* Changed `handleTextChange` to `handleTextOrRadioChange`

Preview storing

---

CHANGELOG.md
app/helpers/research_sessions_helper.rb
app/views/research_sessions/preview.html.erb
app/views/research_sessions/questions/recording.html.erb
app/views/research_sessions/questions/storing.html.erb
app/views/research_sessions/questions/topic.html.erb
spec/helpers/research_sessions_helper_spec.rb

Since the start of live previews, we've been repeating ourselves across those live previews and the final preview with respect to certain params that didn't vary.
Introduce `ResearchSessionsHelper#unvarying_params` as a home for these such that the call sites for `react_component` no longer have this repetition.
The tests are a little noisier with respect to mocking but hopefully this helps with the cost of making copy changes that would require parameter changes in two places.
This also fixes a minor copy bug where the "storing" step in live preview mode would show you (out of step with the other live previews which would show "your child")
🎄 🎅 🎁

CHORE: Unvarying params

---

CHANGELOG.md
app/assets/stylesheets/barnardos/_colours.scss
app/assets/stylesheets/barnardos/_reactive-preview.scss

#[Preview highlighting not visible on some monitors](https://trello.com/c/Vu2Hi3mg)
* Change live preview highlight on step
* Change focus background colour on form input element

Change preview highlighting

---

CHANGELOG.md
app/assets/stylesheets/application.scss
app/assets/stylesheets/barnardos/_research-guidance.scss
app/views/research_sessions/questions/researcher.html.erb
app/views/research_sessions/questions/topic.html.erb

Inform users of Barnardo's research policies and practices on the
researcher and topic step. Create a new visual layout for this
information to be presented in.

Add guidance paragraph to researcher & topic step

---

CHANGELOG.md
app/views/research_sessions/preview.html.erb

Remove hard coded "my child" in consent form

---

.babelrc
.browserslistrc
CHANGELOG.md

Moves browser support into its own file `.browserslistrc` which tidies up `.babelrc` and allows for other systems to eventually use it.
Removes specific IE rules, favouring browsers in use and 2 the latest versions.

Improve which browsers to support inside of Babel

---

CHANGELOG.md
app/models/expenses.rb
app/models/research_session.rb

Instead of required all expenses to be completed we allow the user to continue so long as one expense is filled in.

Make Expenses validations require one expense

---

CHANGELOG.md
app/assets/stylesheets/barnardos/_textfield.scss

Makes the text a lighter grey, by default a black colour was being used that looked too much like completed text.

Style IE11 placeholder text

---

app/assets/stylesheets/barnardos/_textfield.scss

Hotfix for IE placeholder bug in order to make it accessible.

Use accessible colour for placeholder text in IE

---

CHANGELOG.md
app/assets/stylesheets/barnardos/_datefield.scss
app/views/research_sessions/questions/where_when.html.erb

Removes redundant text and also fixes an overflow issue on IE11.

Fix overflow issues with legends on IE

---

app/models/research_session.rb
spec/models/research_session_spec.rb

We had written code to try and allow single expenses to pass validation but it wasn't being enforced on production. This change writes a test to check the validations and fixes the issue in general
Related to (old) PR https://github.com/barnardos/consent-form-builder-rails/pull/207
Apologies to @kittysquee who noticed this weirdness during a code review after it had been merged and I didn't take immediate action then.

Force the fact we allow single expenses to pass

---

app/controllers/research_sessions_controller.rb
spec/controllers/research_sessions_controller_spec.rb

Preview wasn't 404ing as we would have expected it would. This was because `research_session_controller` was handling 404 in its own unique way. This change removes that logic from the controller so it follows the same logic as the rest of the system.

Make sure preview can 404

---

CHANGELOG.md
app/assets/stylesheets/print.scss
app/javascript/components/TopicPurposePreviews/index.test.js
app/models/shared_with.rb
app/views/layouts/application.html.erb
config/locales/en.yml
features/support/step_completions.rb
spec/helpers/barnardos/action_view/form_helper_spec.rb

Uses a system font (Verdana) when printed. This required some sizing changes to be made to accommodate Verdana being larger when used than ProximaNova.
Some other small changes were made:
* A tick was being used for "Barnardo's", this has been replaced with an apostrophe
* Padding was being added to editable text, when printed editable doesn't make sense and the padding looked off when characters were no longer aligned.
This solution has been tested against  `Kyocera TASKalfa 5052ci KM4C35C6` which was the printer that was reported to cause this error.
This example shows the improved apostrophe and no padding on text inputs.

Use system font when printing.

---

CHANGELOG.md
app/javascript/packs/application.js
app/javascript/vendor/google_analytics.js
app/views/layouts/application.html.erb

Adds Google Analytics tracking code to the project. Using the same conventions that were put in place for adding HotJar code.
* Uses the ENV setting of `GOOGLE_ANALYTICS_CODE`, this has been to be added to Heroku

Adds Google Analytics tracking to project

---

frontend/components/PreviewConsentForm/index.css
frontend/components/PrintArea/index.css

It [turns out](https://stackoverflow.com/questions/45527185/css-print-page-break-after-not-working-with-css-grid-layout) that `display: grid;` does not work well with print styles.
Closes #319.

Ensure page break happens before printed consent form

---

CHANGELOG.md
app/views/research_sessions/preview.html.erb

Downcasing the whole sentence was affecting the class names in the Output component as well so I've downcased the recording_method text only instead of the whole thing. 
If I understand correctly, when the recording_method === 'other' it means it's added by user so downcasing the text there might not be the best idea so I have left it as it is.

338 downcasing the recording_method text only not the whole sentence
