Gemfile
They add little, they're annoying, and they're gone
=> Remove boilerplate comments from Gemfile

README.md, app/assets/stylesheets/application.scss, app/assets/stylesheets/barnardos/_button.scss, app/assets/stylesheets/barnardos/_colours.scss, app/views/questions/_age.html.erb, app/views/questions/_name.html.erb, app/views/questions/index.html.erb
Created styles for buttons, supporting keyboard navigation and works for mobile and desktop.
=> Button styles

app/assets/stylesheets/application.scss, app/assets/stylesheets/barnardos/_accessibility.scss, app/views/layouts/application.html.erb
Each page needs to have a link at the top that allows users with screen readers or assistive devices.
=> Skip link css

app/assets/stylesheets/application.scss, app/assets/stylesheets/barnardos/_textarea.scss, app/helpers/barnardos/action_view/form_helpers.rb, app/javascript/components/highlightcontrol.js, app/javascript/packs/application.js, app/views/research_sessions/focus.html.erb, spec/helpers/barnardos/form_helpers_spec.rb, spec/helpers/barnardos/text_area_helper_spec.rb, spec/javascript/components/highlightcontrol_spec.js
Comment now, will finish the error indicator in a couple of hours.
=> Convert research focus text field to Barnardo's textarea

app/assets/stylesheets/app/session_preview.scss, app/assets/stylesheets/application.scss, app/assets/stylesheets/barnardos/_colours.scss, app/controllers/research_sessions_controller.rb, app/helpers/research_sessions_helper.rb, app/presenters/research_session_presenter.rb, app/views/research_sessions/preview.html.erb, config/application.rb, config/locales/en.yml, features/printed_consent_forms.feature, features/step_definitions/question_steps.rb, features/step_definitions/session_review_steps.rb, features/support/rspec_html_matchers.rb, spec/helpers/research_sessions_helper_spec.rb, spec/presenters/research_session_presenter_spec.rb
[After entering my session details I can see a session review](https://trello.com/c/DDNtM82C/15-story-after-entering-my-session-details-i-can-see-a-session-review)
*When* I have filled in my research session details
*I want to* see a preview of the consent form content
*So I *can check that it is accurate and displays the way I want to.
* Submitting session details leads to a session review page
* Session review page contains a preview of the information sheet and consent form
=> Session preview page

app/validators/has_at_least_one_validator.rb, spec/validators/has_at_least_one_validator_spec.rb
De-jankify error messages.
Before:
After:
=> Humanize has_at_least_one_of validator

app/assets/stylesheets/barnardos/_checkbox.scss
=> Display error for checkbox lists if provided

app/assets/stylesheets/application.scss, app/assets/stylesheets/barnardos/_button.scss, app/assets/stylesheets/barnardos/_fieldset.scss, app/assets/stylesheets/barnardos/_textarea.scss, app/assets/stylesheets/barnardos/_textfield.scss, app/assets/stylesheets/barnardos/_type.scss, app/views/research_sessions/researcher.html.erb, features/step_definitions/question_steps.rb
Adjust the spacing of controls and also correct some markup to make it semantically correct, so it's easier to control it's spacing also.
=> Adjust spacing

app/assets/stylesheets/application.scss, app/assets/stylesheets/barnardos/_accessibility.scss, app/assets/stylesheets/barnardos/_back.scss, app/helpers/barnardos/action_view/form_helpers.rb, app/views/research_sessions/age.html.erb, app/views/research_sessions/focus.html.erb, app/views/research_sessions/methodologies.html.erb, app/views/research_sessions/recording.html.erb
Restructure the use of headings to be more accessible and try and get some consistency on sizing.
Added a few helper classes
Fixed issue with textfield and textarea not allow additional label classes
=> Normalise content structure

.rubocop.yml, .rubocop_todo.yml, app/helpers/barnardos/action_view/form_helpers.rb, features/step_definitions/session_review_steps.rb, spec/helpers/barnardos/checkbox_helper_spec.rb, spec/helpers/barnardos/form_helpers_spec.rb, spec/helpers/barnardos/radio_helpers_spec.rb, spec/helpers/barnardos/text_area_helper_spec.rb
- This is the github wrap length
- It's not 80, which is pretty difficult to keep to, but neither is it
120, which is pretty difficult to read
Fire away...
=> Fix line lengths to 100

app/assets/stylesheets/print.scss, app/views/research_sessions/preview.html.erb, app/views/research_sessions/preview_consent_form.html.erb
Added a style so a section can be marked to not print.
Added high weighted selector to make sure sections are hidden.
=> Hide main title when printing.

app/assets/stylesheets/app/consent_form_preview.scss, app/assets/stylesheets/application.scss, app/views/research_sessions/preview_consent_form.html.erb, features/printed_consent_forms.feature, features/step_definitions/consent_form_preview_steps.rb
- Remove the old disabled checkbox
- Add some disabled inputs instead
- Make them nice and wide for people to write in
=> Add name, signature & date to consent form

app/assets/stylesheets/application.scss, app/assets/stylesheets/barnardos/_conditional_subfield.scss, app/javascript/components/conditional_subfields.js, app/javascript/packs/application.js, app/views/research_sessions/methodologies.html.erb, app/views/research_sessions/recording.html.erb, package.json, spec/javascript/components/conditional_subfield_spec.js
Allows a page fragment, containing fields, to be made optionally visible depending on a specified field name and value.
Using this component you can create a section of page that will only show if a checkbox field with a given name has a value of other.
This approach allows the code to be implemented in pure html and js without having to update existing rails helpers. The code can also be used to hide more than one field if needed, and clears the values of fields within the fragment if they are to be hidden.
Markup for the component is documented in conditional_subfield.js and through a collection of tests.
=> Conditional subfield

app/assets/stylesheets/application.scss, app/assets/stylesheets/barnardos/_progress.scss, app/views/gallery/index.html.erb
Provides a visual indicator to allow a user to see their progress through a journey and be able to navigate to the desired step.
=> Progress indicator

README.md, config/database.yml
Added instructions to the Readme to explain how to get the stack up and running to try it out.
=> Put useful stuff in the readme

app/models/research_session/steps.rb, app/views/research_sessions/researcher.html.erb, db/migrate/20170825104045_add_conditional_researcher.rb, db/schema.rb
Update the content in the researcher screen.
Add an option to ask if there is another researcher, and if there is reveal the other researcher field.
=> Update researcher screen

app/models/methodologies.rb, app/models/recording_methods.rb, app/models/research_session.rb, app/models/research_session/steps.rb, app/models/shared_with.rb, app/views/research_sessions/data.html.erb, app/views/research_sessions/methodologies.html.erb, app/views/research_sessions/recording.html.erb, config/locales/en.yml, db/migrate/20170825214510_data_processing.rb, db/schema.rb, features/step_definitions/question_steps.rb, spec/controllers/research_sessions_controller_spec.rb, spec/models/research_session_spec.rb
Creates a screen to capture how data will be used from the research.
=> Data processing

app/assets/stylesheets/application.scss, app/assets/stylesheets/barnardos/_datefield.scss, app/models/research_session/steps.rb, app/views/research_sessions/time_equipment.html.erb, db/migrate/20170826103755_session_time.rb, db/schema.rb, features/step_definitions/question_steps.rb
Add a new screen to capture session start time, duration and equipment required.
=> Session time

app/models/research_session.rb, app/models/research_session/steps.rb, features/step_definitions/question_steps.rb, spec/controllers/research_sessions_controller_spec.rb, spec/models/research_session_spec.rb
Change the order of pages so it is now:
* Researcher
* Topic
* Purpose
* Methodologies
* Recording
* Data
* Time and Equipment
* Incentive
* Preview
=> Re-order pages

app/models/research_session/steps.rb, app/views/research_sessions/expenses.html.erb, db/migrate/20170904155000_expenses.rb, db/schema.rb, features/step_definitions/question_steps.rb
Adds the required fields to the DB and a new screen to capture information related to expenses, as described in :
https://docs.google.com/document/d/1hk7eI9rqzeNMxzrkF4UoJUY9IW-gN-ixQCWnZ6mqYTQ/edit
=> Add expenses

app/models/research_session.rb, app/views/research_sessions/researcher.html.erb, spec/models/research_session_spec.rb
Remove the validation, the validation test and indicate that it's
optional in the label
=> Make researcher phone number optional

app/presenters/research_session_presenter.rb, app/views/research_sessions/_progress.html.erb, app/views/research_sessions/preview.html.erb
Added parameter to preogress indicator to allow indication that we are on the preview stage.
Updated progress indicator to correctly show if the preview screen is the current page.
=> Add step links to preview

app/views/research_sessions/preview.html.erb, spec/factories/research_session.rb, spec/views/research_session/preview.html.erb_spec.rb
Also provide a place to do some context-sensitive testing on the preview
that isn't just the end-to-end happy path of Cuking It
=> Fix preview breaking with a blank date

Gemfile, Gemfile.lock
Still left over, should have been merged previously
=> Remove the vandamme gem

CHANGELOG.md
- Also add the yes/no ordering change
=> Add an unreleased 0.3.0

CHANGELOG.md
Was forgotten by
https://github.com/barnardos/consent-form-builder-rails/pull/128
And now we have Dangerbot to help
=> Add CHANGELOG note for progress bug

Gemfile, Gemfile.lock, features/step_definitions/question_steps.rb, features/support/percy.rb
Since we aren't paying for it, it's making the CI build slow by
uploading images, and it's blocking us de-duping Cucumber steps, remove
it.
=> Remove Percy

features/step_definitions/question_steps.rb, features/support/step_completions.rb
Extract repeated sections into a `StepCompletions` module, such that we
can call `complete_<step_name>_step`. Include `StepCompletions` into the
Cucumber `World` so we can call them from anywhere.
=> De-dupe Cucumber wizard step completions

README.md
Opening because #143 is stalled on an infinite Circle build with no apparent way to fix short of removing the Circle webhook.
=> Correct a readme typo

CHANGELOG.md, config/locales/en.yml, features/support/step_completions.rb
Make label indicate the kind of sentence in which it will be used
=> Change label of location

CHANGELOG.md, app/assets/stylesheets/barnardos/_progress.scss, app/helpers/application_helper.rb, app/models/research_session.rb, app/models/research_session/steps.rb, app/views/research_sessions/_progress.html.erb, app/views/research_sessions/incentives.html.erb, app/views/research_sessions/preview.html.erb, app/views/research_sessions/storing.html.erb, app/views/research_sessions/where_when.html.erb, config/initializers/inflections.rb, config/locales/en.yml, db/migrate/20171101152939_update_renamed_steps.rb, features/step_definitions/question_steps.rb, features/support/preview_checker.rb, features/support/step_completions.rb, spec/controllers/research_sessions_controller_spec.rb, spec/factories/research_session.rb, spec/helpers/application_helper_spec.rb, spec/models/research_session/steps_spec.rb, spec/models/research_session_spec.rb, spec/presenters/research_session_presenter_spec.rb
A range of copy changes and small style tweaks to the navigation bar to give a clearer user experience.
=> Navigation improvements

public/robots.txt
Disallow everything. Goodbye.
> _As a researcher
> I want to make sure my consent form is not searchable in google
> So that my work is not public_
=> Disable search engine indexing

CHANGELOG.md, app/assets/images/add.svg, app/assets/stylesheets/app/research_session_commands.scss, app/assets/stylesheets/application.scss, app/assets/stylesheets/barnardos/_button.scss, app/assets/stylesheets/barnardos/_share.scss, app/controllers/research_sessions_controller.rb, app/helpers/application_helper.rb, app/models/research_session.rb, app/models/research_session/steps.rb, app/presenters/research_session_presenter.rb, app/views/layouts/application.html.erb, app/views/research_sessions/create_a_copy.html.erb, app/views/shared/_share.html.erb, config/locales/en.yml, config/routes.rb, features/create_a_copy.feature, features/step_definitions/aids_for_devops_steps.rb, features/step_definitions/create_a_copy_steps.rb, spec/controllers/research_sessions_controller_spec.rb, spec/models/research_session_spec.rb, spec/presenters/research_session_presenter_spec.rb
> When I have a second (related) research session,
> I want to create a new consent form ,
> so I can avoid typing everything from scratch again.
* The visibility of share/new buttons during the copy interstitial
* Should we have Stay/Leave behaviour for leaving edited steps when using New/Create a copy?
=> Create a copy

CHANGELOG.md, app/assets/stylesheets/barnardos/_lists.scss, app/views/research_sessions/preview.html.erb
=> Add concerns and complaints

app/helpers/research_sessions_helper.rb, app/models/recording_methods.rb, app/presenters/research_session_presenter.rb, app/views/research_sessions/preview.html.erb, app/views/research_sessions/questions/recording.html.erb, db/migrate/20171204115351_update_recording_methods.rb, db/schema.rb, features/step_definitions/session_review_steps.rb, features/support/step_completions.rb, spec/controllers/research_sessions/questions_controller_spec.rb, spec/factories/research_session.rb, spec/helpers/research_sessions_helper_spec.rb, spec/presenters/research_session_presenter_spec.rb
> _As a research participant
> I want my Information Sheet to be as simple as possible
> So that I can understand what I am consenting to_
=> Update recording list

CHANGELOG.md, app/views/research_sessions/preview.html.erb
=> Add "About taking part" to the info sheet (static)

CHANGELOG.md, app/assets/stylesheets/barnardos/_lists.scss, app/views/research_sessions/preview.html.erb
Add a new section for participants to understand what they / the
person in their custody is taking part in. Create a new class to
have a numbered list.
=> Add 'decide if you want take part' section

CHANGELOG.md, app/helpers/barnardos/action_view/form_helper.rb, app/helpers/research_sessions_helper.rb, app/javascript/components/RecordingMethodsPreviews/index.js, app/javascript/components/RecordingMethodsPreviews/index.test.js, app/javascript/components/ResearcherPreviews/index.js, app/javascript/components/ResearcherPreviews/index.test.js, app/javascript/components/Shared/Output.js, app/javascript/components/Shared/Output.test.js, app/javascript/components/Shared/PreviewBase.js, app/javascript/components/Shared/WhichWeWillRecordUsing.js, app/javascript/components/Shared/WhichWeWillRecordUsingList.js, app/javascript/components/Shared/WhichWeWillRecordUsingSentence.js, app/javascript/components/Shared/sort-against.js, app/javascript/components/Shared/sort-against.test.js, app/javascript/components/TopicPurposePreviews/index.test.js, app/views/research_sessions/preview.html.erb, app/views/research_sessions/questions/recording.html.erb, package.json, spec/helpers/barnardos/action_view/form_helper_spec.rb, spec/helpers/research_sessions_helper_spec.rb, yarn.lock
> As a researcher
> I want to see how I am affecting the preview as I edit live values
> So that my changes are obvious and I don't have to skip between steps
I'd like to explore styling issues with @joelcarr:
=> Live Preview: Recording methods

CHANGELOG.md, README.md
* Change `start` to `server` in Rails server start instructions
=> Change start to server in README

CHANGELOG.md, app/javascript/components/Shared/SessionDetails.js, app/javascript/components/WhereWhenPreviews/index.js, app/javascript/components/WhereWhenPreviews/index.test.js, app/views/research_sessions/preview.html.erb, app/views/research_sessions/questions/where_when.html.erb, package-lock.json, package.json
* Create new live preview component
* Add appropriate tests
=> Add live preview to Where and When section

CHANGELOG.md, config/environments/production.rb
=> Enforce https

CHANGELOG.md, app/javascript/components/IncentivesPreviews/index.js, app/javascript/components/IncentivesPreviews/index.test.js, app/javascript/components/Shared/Incentives.js, app/presenters/research_session_presenter.rb, app/views/research_sessions/preview.html.erb, app/views/research_sessions/questions/incentives.html.erb, features/support/preview_checker.rb, spec/presenters/research_session_presenter_spec.rb
* Create live preview component for Incentives
* Use React component on step and final preview
=> Live preview incentives

CHANGELOG.md, README.md
* This will rectify issues with running rake
=> Update README with PostgreSQL user upgrade

CHANGELOG.md, README.md
Closes #140 (doesn't have a trello ticket, this was an early branch we just want to get rid of)
=> Fixing some spelling errors

CHANGELOG.md
=> Release 0.8.1

CHANGELOG.md, app/javascript/components/RecordingMethodsPreviews/index.test.js, app/javascript/components/Shared/WillAnyoneKnowWhatISayInTheDiscussion.js, app/models/recording_methods.rb, app/views/research_sessions/preview.html.erb, features/step_definitions/session_review_steps.rb, features/support/step_completions.rb, spec/presenters/research_session_presenter_spec.rb
=> Fix content based on user testing

CHANGELOG.md
=> Release 0.8.2

README.md
I will close the ticket  #1 'Documentation review' manually which is under BAU. 
I have checked Digital transformation and FGM along with consent form Readme and digital transformation and FGM seem to be fine.
I've made several updates to consent form Readme. I would also like to remove the todo as I've added the 'rake' testing bit to the readme and not sure we need to add the other two. @tosbourn and @kittysquee please let me know if anything needs changing and if you are happy for me to remove the to do section at the bottom of readme.
=> Update consent form Readme installation and deployment

app/views/research_sessions/questions/methodologies.html.erb, app/views/research_sessions/questions/recording.html.erb, app/views/research_sessions/questions/storing.html.erb, frontend/components/OfManyChoiceControl/_index.html.erb
=> Align storing page to the design system

app/views/research_sessions/questions/storing.html.erb, app/views/research_sessions/questions/where_when.html.erb, frontend/components/ChoiceControlledContent/index.css
@joelcarr I've added the components, however have realised if single text line components used under another component then there is no space between the components. Will we need to add our own css to this and where do you suggest adding it?
=> Where and when

.eslintignore, app/views/layouts/application.html.erb, frontend/packs/application.js, frontend/vendor/GoogleAnalytics.js, frontend/vendor/Hotjar.js, package.json
=> Add Hotjar and Google analytics

.stylelintrc, app/views/research_sessions/questions/expenses.html.erb, app/views/research_sessions/questions/incentives.html.erb, app/views/research_sessions/questions/methodologies.html.erb, app/views/research_sessions/questions/recording.html.erb, app/views/research_sessions/questions/researcher.html.erb, app/views/research_sessions/questions/storing.html.erb, app/views/research_sessions/questions/topic.html.erb, app/views/research_sessions/questions/where_when.html.erb, frontend/components/ErrorSummary/index.css, frontend/components/Form/index.css, frontend/components/HeadingOne/index.css, frontend/components/Layout/index.css, frontend/components/Lede/index.css, frontend/components/OfManyChoiceControl/index.css, frontend/components/OrderedList/index.css, frontend/components/Paragraph/index.css, frontend/components/PreviewConsentForm/index.css, frontend/components/Step/index.css, frontend/components/Title/index.css, frontend/components/UnorderedList/index.css, frontend/components/WritingFields/index.css
=> Step preview layout

CHANGELOG.md, app/controllers/start_pages_controller.rb, app/helpers/application_helper.rb, app/views/start_pages/show.html.erb, config/locales/en.yml, config/routes.rb, features/aids_for_devops.feature, features/step_definitions/aids_for_devops_steps.rb, features/support/step_completions.rb, frontend/components/StartLink/_index.html.erb, frontend/components/StartLink/index.css, frontend/components/StartLink/index.js, frontend/packs/application.js
Closes #322 by adding a start page with the agreed upon text and components.
Uses in progress work from https://github.com/barnardos/design-system/pull/172
=> Adds start page

CHANGELOG.md, frontend/components/Header/index.css
=> Fix logo so it scales proportionally

CHANGELOG.md, app/views/research_sessions/questions/researcher.html.erb, app/views/research_sessions/questions/where_when.html.erb
=> Size controls consistently

CHANGELOG.md, app/models/methodologies.rb, app/models/recording_methods.rb, app/models/shared_with.rb, app/views/research_sessions/preview.html.erb, app/views/research_sessions/questions/expenses.html.erb, app/views/research_sessions/questions/incentives.html.erb, app/views/research_sessions/questions/methodologies.html.erb, app/views/research_sessions/questions/recording.html.erb, app/views/research_sessions/questions/researcher.html.erb, app/views/research_sessions/questions/storing.html.erb, app/views/research_sessions/questions/where_when.html.erb, config/locales/en.yml, features/printed_consent_forms.feature, features/step_definitions/aids_for_devops_steps.rb, features/step_definitions/create_a_copy_steps.rb, features/step_definitions/question_steps.rb, features/step_definitions/session_review_steps.rb, features/support/preview_checker.rb, features/support/step_completions.rb, frontend/components/Fieldset/_index.html.erb, frontend/components/Fieldset/index.css, frontend/components/Fieldset/index.js, frontend/packs/application.js, spec/helpers/barnardos/action_view/form_helper_spec.rb
@joelcarr On expenses page where I've added fieldset the inputs are not applying the grid rule. Seems like this does not work on fieldsets? What's the best way to fix this?
Closes #313.
=> Improves labels/content and fieldset component added

CHANGELOG.md, app/views/research_sessions/questions/researcher.html.erb, config/locales/en.yml, features/support/preview_checker.rb
=> Fixes copy on the preview page

CHANGELOG.md
=> Release 2.0.2

package.json, yarn.lock
Github had flagged that there was a potential security issue with webpack-dev-server so updated to address. 
https://github.com/barnardos/consent-form-builder/network/alert/package.json/webpack-dev-server/open
=> Updates webpack-dev-server due to security issue

CHANGELOG.md, Gemfile, Gemfile.lock, app/views/research_sessions/questions/researcher.html.erb, app/views/start_pages/show.html.erb, config/locales/en.yml
Fixes #433 
PR Review link:
https://consent-form-builder-st-pr-434.herokuapp.com
=> changing BREC link from hive to inside.barnardos
